ALTER TYPE "CompanyVisualPreference" RENAME VALUE 'SYSTEM' TO 'AUTO';

CREATE TYPE "CompanyVisualStyle" AS ENUM ('MINIMAL', 'MODERN', 'PREMIUM', 'BOLD');

ALTER TABLE "Company"
ADD COLUMN "backgroundColor" TEXT NOT NULL DEFAULT '#F8FAFC',
ADD COLUMN "surfaceColor" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN "textColor" TEXT NOT NULL DEFAULT '#0F172A',
ADD COLUMN "visualStyle" "CompanyVisualStyle" NOT NULL DEFAULT 'MINIMAL',
ADD COLUMN "borderRadius" TEXT NOT NULL DEFAULT 'MEDIUM';
